# Copyright 2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.7"

networks:
  gameroom:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  cargo-registry:
  registry:
  acme-keys:
  bubba-keys:
  acme-var:
  bubba-var:
  acme-db:
  bubba-db:

services:

    generate-registry:
        image: splintercommunity/splinter-cli:master
        networks:
          gameroom:
            ipv4_address: 172.28.1.1
        volumes:
          - registry:/registry
        command: |
          bash -c "
            if [ ! -f /registry/registry.yaml ]
            then
              # generate keys
              splinter admin keygen alice -d /registry
              splinter admin keygen bob -d /registry
              # check if splinterd-node-acme is available
              while [[ $$(curl --write-out %{http_code} --silent --output /dev/null http://splinterd-node-acme:8085/status) -ne 200 ]] ; do
                 >&2 echo \"splinterd is unavailable - sleeping\"
                 sleep 1
              done
              # check if splinterd-node-bubba is available
              while [[ $$(curl --write-out %{http_code} --silent --output /dev/null http://splinterd-node-bubba:8085/status) -ne 200 ]] ; do
                 >&2 echo \"splinterd is unavailable - sleeping\"
                 sleep 1
              done
              # build the registry
              splinter registry build \
                http://splinterd-node-acme:8085 \
                --file /registry/registry.yaml \
                --key-file /registry/alice.pub \
                --metadata organization='ACME Corporation'
              splinter registry build \
                http://splinterd-node-bubba:8085 \
                --file /registry/registry.yaml \
                --key-file /registry/bob.pub \
                --metadata organization='Bubba Bakery'
            fi
          "

    registry-server:
      image: httpd:2.4
      container_name: registry-server
      restart: always
      expose:
        - 80
      ports:
          - "8099:80"
      networks:
        gameroom:
          ipv4_address: 172.28.1.2
      volumes:
        - registry:/usr/local/apache2/htdocs

    db-acme:
      image: splintercommunity/gameroom-database:master
      container_name: db-acme
      restart: always
      expose:
        - 5432
      ports:
          - "5432:5432"
      environment:
        POSTGRES_USER: gameroom
        POSTGRES_PASSWORD: gameroom_example
        POSTGRES_DB: gameroom
      networks:
        gameroom:
          ipv4_address: 172.28.2.1
      volumes:
        - acme-db:/var/lib/postgresql/data/

    gameroom-app-acme:
      image: splintercommunity/gameroom-app-acme:master
      container_name: gameroom-app-acme
      networks:
        gameroom:
          ipv4_address: 172.28.2.2
      environment:
        - VUE_APP_BRAND=acme
      expose:
        - 80
      ports:
        - '8080:80'

    gameroomd-acme:
        image: splintercommunity/gameroomd:master
        container_name: gameroomd-acme
        networks:
          gameroom:
            ipv4_address: 172.28.2.3
        volumes:
          - acme-keys:/keys
          - cargo-registry:/root/.cargo/registry
        expose:
          - 8000
        ports:
          - "8000:8000"
        depends_on:
          - splinterd-node-acme
        command: |
          bash -c "
            # we need to wait for the db to have started.
            until PGPASSWORD=gameroom_example psql -h db-acme -U gameroom -c '\q'; do
                >&2 echo \"Database is unavailable - sleeping\"
                sleep 1
            done

            # check if splinterd-node-acme is available
            while [[ $$(curl --write-out %{http_code} --silent --output /dev/null http://splinterd-node-acme:8085/status) -ne 200 ]] ; do
               >&2 echo \"splinterd is unavailable - sleeping\"
               sleep 1
            done

            gameroom -vv database migrate --database-url postgres://gameroom:gameroom_example@db-acme:5432/gameroom &&
            gameroomd -vv --database-url postgres://gameroom:gameroom_example@db-acme:5432/gameroom \
              -b gameroomd-acme:8000 \
              --splinterd-url http://splinterd-node-acme:8085 \
              --key /keys/acme.priv
          "

    splinterd-node-acme:
      image: splintercommunity/splinterd:master
      container_name: splinterd-node-acme
      expose:
        - 8080
        - 8044
        - 8945
        - 8085
      ports:
        - 8088:8085
      networks:
        gameroom:
          ipv4_address: 172.28.2.4
      volumes:
        - acme-keys:/keys
        - acme-var:/var/lib/splinter
        - ./splinterd-config:/configs
      entrypoint: |
        bash -c "
          if [ ! -f /keys/acme.priv ]
          then
            splinter admin keygen acme -d /keys
          fi && \
          until PGPASSWORD=admin psql -h splinterd-db-acme -U admin -d splinter -c '\q'; do
            >&2 echo \"Database is unavailable - sleeping\"
            sleep 1
          done && \
          splinter database migrate -C postgres://admin:admin@splinterd-db-acme:5432/splinter && \
          splinter cert generate --skip && \
          splinterd -c ./configs/splinterd-node-acme.toml -vv \
              --database postgres://admin:admin@splinterd-db-acme:5432/splinter \
              --network-endpoints tcps://0.0.0.0:8044 \
              --advertised-endpoints tcps://splinterd-node-acme:8044 \
              --rest-api-endpoint 0.0.0.0:8085 \
              --registries http://registry-server:80/registry.yaml \
              --tls-insecure \
              --enable-biome
        "

    splinterd-db-acme:
      image: postgres
      container_name: splinterd-db-acme
      restart: always
      expose:
        - 5432
      ports:
        - "5435:5432"
      networks:
        gameroom:
          ipv4_address: 172.28.2.5
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: splinter

    db-bubba:
      image: splintercommunity/gameroom-database:master
      container_name: db-bubba
      restart: always
      networks:
        gameroom:
          ipv4_address: 172.28.3.1
      expose:
        - 5432
      ports:
          - "5433:5432"
      environment:
        POSTGRES_USER: gameroom
        POSTGRES_PASSWORD: gameroom_example
        POSTGRES_DB: gameroom
      volumes:
        - bubba-db:/var/lib/postgresql/data/

    gameroom-app-bubba:
      image: splintercommunity/gameroom-app-bubba:master
      container_name: gameroom-app-bubba
      networks:
        gameroom:
          ipv4_address: 172.28.3.2
      environment:
        - VUE_APP_BRAND=bubba
      expose:
        - 80
      ports:
        - '8081:80'

    gameroomd-bubba:
        image: splintercommunity/gameroomd:master
        container_name: gameroomd-bubba
        networks:
          gameroom:
            ipv4_address: 172.28.3.3
        volumes:
          - bubba-keys:/keys
          - cargo-registry:/root/.cargo/registry
        expose:
          - 8000
        ports:
          - "8001:8000"
        depends_on:
          - splinterd-node-bubba
        command: |
          bash -c "
            # we need to wait for the db to have started.
            until PGPASSWORD=gameroom_example psql -h db-bubba -U gameroom -c '\q'; do
                >&2 echo \"Database is unavailable - sleeping\"
                sleep 1
            done

            # check if splinterd-node-bubba is available
            while [[ $$(curl --write-out %{http_code} --silent --output /dev/null http://splinterd-node-bubba:8085/status) -ne 200 ]] ; do
               >&2 echo \"splinterd is unavailable - sleeping\"
               sleep 1
            done

            gameroom -vv database migrate --database-url postgres://gameroom:gameroom_example@db-bubba:5432/gameroom &&
            gameroomd -vv --database-url postgres://gameroom:gameroom_example@db-bubba:5432/gameroom \
              -b gameroomd-bubba:8000 \
              --splinterd-url http://splinterd-node-bubba:8085 \
              --key /keys/bubba.priv
          "

    splinterd-node-bubba:
      image: splintercommunity/splinterd:master
      container_name: splinterd-node-bubba
      expose:
        - 8080
        - 8044
        - 8945
        - 8085
      ports:
        - 8089:8085
      networks:
        gameroom:
          ipv4_address: 172.28.3.4
      volumes:
        - bubba-keys:/keys
        - ./splinterd-config:/configs
        - bubba-var:/var/lib/splinter
      entrypoint: |
        bash -c "
          if [ ! -f /keys/bubba.priv ]
          then
            splinter admin keygen bubba -d /keys
          fi && \
          until PGPASSWORD=admin psql -h splinterd-db-bubba -U admin -d splinter -c '\q'; do
            >&2 echo \"Database is unavailable - sleeping\"
            sleep 1
          done && \
          splinter database migrate -C postgres://admin:admin@splinterd-db-bubba:5432/splinter && \
          splinter cert generate --skip && \
          splinterd -c ./configs/splinterd-node-bubba.toml -vv \
              --database postgres://admin:admin@splinterd-db-acme:5432/splinter \
              --network-endpoints tcps://0.0.0.0:8044 \
              --advertised-endpoints tcps://splinterd-node-bubba:8044 \
              --rest-api-endpoint 0.0.0.0:8085 \
              --registries http://registry-server:80/registry.yaml \
              --tls-insecure \
              --enable-biome
        "

    splinterd-db-bubba:
      image: postgres
      container_name: splinterd-db-bubba
      restart: always
      expose:
        - 5432
      ports:
        - "5434:5432"
      networks:
        gameroom:
          ipv4_address: 172.28.3.5
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: splinter
