name: 0-4 Merge

on:
  push:
    branches:
      - 0-4

env:
  CARGO_TERM_COLOR: always

jobs:

  lint_gameroom_client:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Lint Gameroom Client
        run: just ci-lint-client

  lint_splinter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Run Lint/Clippy on Splinter
        run: just ci-lint-splinter

  unit_test_splinter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Unit Test Splinter
        run: just ci-test

  gameroom_tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Gameroom Tests
        run: just ci-test-gameroom

  gameroom_ui_tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Gameroom UI Tests
        run: just ci-test-gameroom-ui
